-d C:\Users\prana\Desktop\4-Personal_Projects\FPGA-projects\FPGA\fpga-code\GOA_project\impl\gwsynthesis\GOA_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\prana\Desktop\4-Personal_Projects\FPGA-projects\FPGA\fpga-code\GOA_project\src\GOA_project.cst
-cfg C:\Users\prana\Desktop\4-Personal_Projects\FPGA-projects\FPGA\fpga-code\GOA_project\impl\pnr\device.cfg
-gao_crc 0100011000000001
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
-rtl_gao
